spring:
  datasource:
    url: "jdbc:mysql://localhost/overtime"
    driverClassName: "com.mysql.jdbc.Driver"
    username: overtime
    password: overtime-passwd
  jpa.hibernate.ddl-auto: create-drop